// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Oqtane.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Oqtane.Survey.Server.Repository
{
    public partial class OqtaneSurvey : IAuditable
    {
        public OqtaneSurvey()
        {
            OqtaneSurveyItem = new HashSet<OqtaneSurveyItem>();
        }

        [Key]
        public int SurveyId { get; set; }
        public int? UserId { get; set; }
        public int ModuleId { get; set; }
        public string SurveyName { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }

        public virtual ICollection<OqtaneSurveyItem> OqtaneSurveyItem { get; set; }
    }
}