// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Oqtane.Survey.Server.Repository
{
    public partial class OqtaneSurveyItem
    {
        public OqtaneSurveyItem()
        {
            OqtaneSurveyAnswer = new HashSet<OqtaneSurveyAnswer>();
            OqtaneSurveyItemOption = new HashSet<OqtaneSurveyItemOption>();
        }

        public int Id { get; set; }
        public int Survey { get; set; }
        public string ItemLabel { get; set; }
        public string ItemType { get; set; }
        public string ItemValue { get; set; }
        public int Position { get; set; }
        public int Required { get; set; }
        public int? SurveyChoiceId { get; set; }

        public virtual OqtaneSurvey SurveyNavigation { get; set; }
        public virtual ICollection<OqtaneSurveyAnswer> OqtaneSurveyAnswer { get; set; }
        public virtual ICollection<OqtaneSurveyItemOption> OqtaneSurveyItemOption { get; set; }
    }
}